######################################################################
# Automatically generated by qmake (3.1) Fri Sep 13 11:07:18 2019
######################################################################

QT += testlib core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
SOURCES += testesunitarios.cpp
SOURCES += \
	$$files(../src/*.cpp)
# Excluding main for program
SOURCES -= \
	../src/main.cpp
HEADERS += \
	../src/*.h
FORMS += \
        ../src/*.ui
